<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><UseWPF>true</UseWPF>
    <AssemblyName>WindowsStorageCleaner</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Cleaner.Core/Cleaner.Core.csproj" /></ItemGroup>
</Project>
